### ISSUE TITLE
How to cite this program cg_param_m3?

### ISSUE THREAD

**Issue by supernova4869** [cgkmw-durham/cg_param_m3#3]
Hello. I know that if I used cg_param, I should cite Miller's paper(J. Chem. Theory Comput. 2021, 17, 9, 5777–5791). But if I used this program cg_param_m3, how should I cite it? Should I cite this project?

**Comment by EKearn** [comment]
Hi there,

Apologies for the slow response! We published the Martini 3 version of the script in the follow paper: 

T.D. Potter, N. Haywood, A. Teixeira, G. Hodges, E.L. Barrett and M.A. Miller, Partitioning into phosphatidylcholine–cholesterol membranes: liposome measurements, coarse-grained simulations, and implications for bioaccumulation, Environ. Sci.: Processes Impacts, 2023, 25, 1082-1093

Using the 2021 paper is okay as the fundamentals of the code are included there, but the 2023 paper is the proper reference.

Thanks for using the code!

**Comment by supernova4869** [comment]
> Hi there,
> 
> Apologies for the slow response! We published the Martini 3 version of the script in the follow paper:
> 
> T.D. Potter, N. Haywood, A. Teixeira, G. Hodges, E.L. Barrett and M.A. Miller, Partitioning into phosphatidylcholine–cholesterol membranes: liposome measurements, coarse-grained simulations, and implications for bioaccumulation, Environ. Sci.: Processes Impacts, 2023, 25, 1082-1093
> 
> Using the 2021 paper is okay as the fundamentals of the code are included there, but the 2023 paper is the proper reference.
> 
> Thanks for using the code!

Thank you! I will cite the paper in our research.
